import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const skills = [
  {
    title: "Java Programming",
    description: "Core Java programming concepts, OOP, collections, and best practices",
    category: "Programming",
  },
  {
    title: "Python Programming",
    description: "Python fundamentals, data structures, and common libraries",
    category: "Programming",
  },
  {
    title: "Web Development",
    description: "HTML, CSS, JavaScript, and modern web development practices",
    category: "Web Development",
  },
  {
    title: "Data Structures & Algorithms",
    description: "Core DSA concepts, complexity analysis, and problem-solving",
    category: "DSA",
  },
  {
    title: "Database Management Systems",
    description: "SQL, database design, normalization, and query optimization",
    category: "Database",
  },
  {
    title: "Machine Learning",
    description: "ML algorithms, model training, evaluation, and deployment",
    category: "AI & Data Science",
  },
  {
    title: "System Design",
    description: "Scalable system architecture, distributed systems, and design patterns",
    category: "System Design",
  },
  {
    title: "JavaScript",
    description: "JavaScript fundamentals, ES6+, async programming, and DOM manipulation",
    category: "Programming",
  },
  {
    title: "React.js",
    description: "React components, hooks, state management, and best practices",
    category: "Web Development",
  },
  {
    title: "Backend Development",
    description: "Server-side development, APIs, authentication, and database integration",
    category: "Backend",
  },
];

// Comprehensive questions for each skill (20 questions each)
const questionsBySkill: Record<string, any[]> = {
  "Java Programming": [
    // BEGINNER (8 questions)
    {
      question_text: "What is the primary purpose of the 'final' keyword in Java?",
      options: ["To make a variable constant", "To prevent method overriding", "To prevent class inheritance", "All of the above"],
      correct_answer: 3,
      question_type: "conceptual",
      difficulty: "BEGINNER",
      explanation: "The 'final' keyword can be used for variables (constants), methods (prevent overriding), and classes (prevent inheritance).",
      points: 1,
    },
    {
      question_text: "What is the difference between == and .equals() in Java?",
      options: [
        "== compares references, .equals() compares values",
        ".equals() compares references, == compares values",
        "They are identical",
        "== only works for primitives",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "BEGINNER",
      explanation: "== compares object references (memory addresses), while .equals() compares the actual content/values of objects.",
      points: 1,
    },
    {
      question_text: "What is the default value of an int variable in Java?",
      options: ["0", "null", "undefined", "1"],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "BEGINNER",
      explanation: "Primitive types in Java have default values. int defaults to 0.",
      points: 1,
    },
    {
      question_text: "Which collection class is synchronized in Java?",
      options: ["ArrayList", "Vector", "LinkedList", "HashSet"],
      correct_answer: 1,
      question_type: "conceptual",
      difficulty: "BEGINNER",
      explanation: "Vector is synchronized (thread-safe), while ArrayList, LinkedList, and HashSet are not.",
      points: 1,
    },
    {
      question_text: "What is the superclass of all classes in Java?",
      options: ["Object", "Class", "Super", "Parent"],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "BEGINNER",
      explanation: "Object is the root class of the Java class hierarchy. All classes inherit from Object.",
      points: 1,
    },
    {
      question_text: "Write a Java method to check if a number is even.",
      options: [
        "public boolean isEven(int n) { return n % 2 == 0; }",
        "public boolean isEven(int n) { return n / 2 == 0; }",
        "public boolean isEven(int n) { return n * 2 == 0; }",
        "public boolean isEven(int n) { return n - 2 == 0; }",
      ],
      correct_answer: 0,
      question_type: "practical",
      difficulty: "BEGINNER",
      explanation: "The modulo operator (%) returns the remainder. If n % 2 == 0, the number is even.",
      points: 1,
    },
    {
      question_text: "What is an interface in Java?",
      options: [
        "A class that cannot be instantiated",
        "A contract that defines methods a class must implement",
        "A data structure",
        "A variable type",
      ],
      correct_answer: 1,
      question_type: "conceptual",
      difficulty: "BEGINNER",
      explanation: "An interface defines a contract - it specifies methods that implementing classes must provide.",
      points: 1,
    },
    {
      question_text: "You need to store unique elements. Which collection should you use?",
      options: ["ArrayList", "HashSet", "LinkedList", "Array"],
      correct_answer: 1,
      question_type: "scenario",
      difficulty: "BEGINNER",
      explanation: "HashSet automatically ensures uniqueness of elements, which is perfect for this requirement.",
      points: 1,
    },
    // INTERMEDIATE (8 questions)
    {
      question_text: "What is the difference between ArrayList and LinkedList in Java?",
      options: [
        "ArrayList is faster for random access, LinkedList is faster for insertions/deletions",
        "LinkedList is faster for random access, ArrayList is faster for insertions/deletions",
        "They are identical in performance",
        "ArrayList can only store primitives",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "INTERMEDIATE",
      explanation: "ArrayList uses dynamic arrays (O(1) access, O(n) insert/delete), while LinkedList uses nodes (O(n) access, O(1) insert/delete).",
      points: 1,
    },
    {
      question_text: "Write a Java method to reverse a string without using StringBuilder.",
      options: [
        "public String reverse(String str) { return new StringBuilder(str).reverse().toString(); }",
        "public String reverse(String str) { char[] chars = str.toCharArray(); for(int i=0, j=chars.length-1; i<j; i++, j--) { char temp = chars[i]; chars[i] = chars[j]; chars[j] = temp; } return new String(chars); }",
        "public String reverse(String str) { return str.split('').reverse().join(''); }",
        "public String reverse(String str) { return str.reverse(); }",
      ],
      correct_answer: 1,
      question_type: "practical",
      difficulty: "INTERMEDIATE",
      explanation: "The correct solution uses a two-pointer approach to swap characters in a char array without using StringBuilder.",
      points: 1,
    },
    {
      question_text: "What is method overloading in Java?",
      options: [
        "Having multiple methods with the same name but different parameters",
        "Having multiple methods with different names",
        "Inheriting methods from a parent class",
        "Overriding a method from a parent class",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "INTERMEDIATE",
      explanation: "Method overloading allows multiple methods with the same name but different parameter lists (different types or number of parameters).",
      points: 1,
    },
    {
      question_text: "What is the difference between checked and unchecked exceptions?",
      options: [
        "Checked exceptions must be handled, unchecked don't",
        "Unchecked exceptions must be handled, checked don't",
        "They are the same",
        "Checked exceptions are for errors only",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "INTERMEDIATE",
      explanation: "Checked exceptions (like IOException) must be declared or caught, while unchecked exceptions (like RuntimeException) don't require handling.",
      points: 1,
    },
    {
      question_text: "Write a Java method to find the maximum value in an array.",
      options: [
        "public int findMax(int[] arr) { int max = arr[0]; for(int i=1; i<arr.length; i++) { if(arr[i] > max) max = arr[i]; } return max; }",
        "public int findMax(int[] arr) { return arr[arr.length-1]; }",
        "public int findMax(int[] arr) { return arr[0]; }",
        "public int findMax(int[] arr) { return arr.length; }",
      ],
      correct_answer: 0,
      question_type: "practical",
      difficulty: "INTERMEDIATE",
      explanation: "The correct solution iterates through the array, comparing each element with the current maximum.",
      points: 1,
    },
    {
      question_text: "What is the purpose of the 'static' keyword in Java?",
      options: [
        "To make a variable constant",
        "To make a method or variable belong to the class rather than instances",
        "To prevent inheritance",
        "To make a class final",
      ],
      correct_answer: 1,
      question_type: "conceptual",
      difficulty: "INTERMEDIATE",
      explanation: "Static members belong to the class itself, not to instances. They can be accessed without creating an object.",
      points: 1,
    },
    {
      question_text: "You are building a caching system. Which collection would be best for key-value pairs with fast lookup?",
      options: ["ArrayList", "HashMap", "LinkedList", "HashSet"],
      correct_answer: 1,
      question_type: "scenario",
      difficulty: "INTERMEDIATE",
      explanation: "HashMap provides O(1) average-case lookup time for key-value pairs, making it ideal for caching.",
      points: 1,
    },
    {
      question_text: "What is the time complexity of searching in a HashMap?",
      options: ["O(n)", "O(log n)", "O(1) average case", "O(n log n)"],
      correct_answer: 2,
      question_type: "conceptual",
      difficulty: "INTERMEDIATE",
      explanation: "HashMap provides O(1) average-case time complexity for search operations, though worst case can be O(n).",
      points: 1,
    },
    // ADVANCED (4 questions)
    {
      question_text: "You are building a multi-threaded application. How would you ensure thread safety when multiple threads access a shared counter?",
      options: [
        "Use synchronized keyword on the increment method",
        "Use AtomicInteger class",
        "Use volatile keyword on the counter variable",
        "Both A and B are correct",
      ],
      correct_answer: 3,
      question_type: "scenario",
      difficulty: "ADVANCED",
      explanation: "Both synchronized methods and AtomicInteger provide thread safety. AtomicInteger is more efficient for simple operations.",
      points: 1,
    },
    {
      question_text: "What is the difference between String, StringBuffer, and StringBuilder?",
      options: [
        "String is immutable, StringBuffer is mutable and synchronized, StringBuilder is mutable and not synchronized",
        "They are all identical",
        "StringBuffer is immutable, StringBuilder is mutable",
        "String is mutable, others are immutable",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "ADVANCED",
      explanation: "String is immutable. StringBuffer is mutable and thread-safe (synchronized). StringBuilder is mutable but not thread-safe (faster).",
      points: 1,
    },
    {
      question_text: "Write a Java method to implement a binary search algorithm.",
      options: [
        "public int binarySearch(int[] arr, int target) { int left = 0, right = arr.length - 1; while(left <= right) { int mid = left + (right - left) / 2; if(arr[mid] == target) return mid; if(arr[mid] < target) left = mid + 1; else right = mid - 1; } return -1; }",
        "public int binarySearch(int[] arr, int target) { for(int i=0; i<arr.length; i++) { if(arr[i] == target) return i; } return -1; }",
        "public int binarySearch(int[] arr, int target) { return arr[target]; }",
        "public int binarySearch(int[] arr, int target) { return arr.length; }",
      ],
      correct_answer: 0,
      question_type: "practical",
      difficulty: "ADVANCED",
      explanation: "Binary search requires a sorted array and uses divide-and-conquer to find the target in O(log n) time.",
      points: 1,
    },
    {
      question_text: "You need to design a system that processes tasks asynchronously. Which Java concurrency utility would be best?",
      options: ["Thread class", "ExecutorService", "synchronized keyword", "volatile keyword"],
      correct_answer: 1,
      question_type: "scenario",
      difficulty: "ADVANCED",
      explanation: "ExecutorService provides a high-level API for managing thread pools and asynchronous task execution, which is ideal for this use case.",
      points: 1,
    },
  ],
  "Python Programming": [
    // BEGINNER (8 questions)
    {
      question_text: "What is the difference between a list and a tuple in Python?",
      options: [
        "Lists are mutable, tuples are immutable",
        "Tuples are mutable, lists are immutable",
        "They are identical",
        "Lists can only store numbers",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "BEGINNER",
      explanation: "Lists can be modified after creation (mutable), while tuples cannot (immutable).",
      points: 1,
    },
    {
      question_text: "What does the 'with' statement do in Python?",
      options: [
        "It creates a new variable scope",
        "It ensures proper resource management and automatic cleanup",
        "It is used for loops",
        "It imports modules",
      ],
      correct_answer: 1,
      question_type: "conceptual",
      difficulty: "BEGINNER",
      explanation: "The 'with' statement provides automatic resource management, ensuring cleanup even if exceptions occur.",
      points: 1,
    },
    {
      question_text: "How do you create an empty dictionary in Python?",
      options: ["{}", "dict()", "Both A and B", "[]"],
      correct_answer: 2,
      question_type: "conceptual",
      difficulty: "BEGINNER",
      explanation: "Both {} and dict() create empty dictionaries in Python.",
      points: 1,
    },
    {
      question_text: "What is a list comprehension in Python?",
      options: [
        "A way to create lists using a concise syntax",
        "A method to sort lists",
        "A way to delete list elements",
        "A type of loop",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "BEGINNER",
      explanation: "List comprehensions provide a concise way to create lists based on existing iterables.",
      points: 1,
    },
    {
      question_text: "Write a Python function to find the factorial of a number using recursion.",
      options: [
        "def factorial(n): return n * factorial(n-1) if n > 1 else 1",
        "def factorial(n): return n * factorial(n-1)",
        "def factorial(n): return factorial(n) * factorial(n-1)",
        "def factorial(n): return n * (n-1)",
      ],
      correct_answer: 0,
      question_type: "practical",
      difficulty: "BEGINNER",
      explanation: "The correct recursive function includes a base case (n <= 1 returns 1) to prevent infinite recursion.",
      points: 1,
    },
    {
      question_text: "What is the difference between 'is' and '==' in Python?",
      options: [
        "'is' checks identity (same object), '==' checks equality (same value)",
        "'==' checks identity, 'is' checks equality",
        "They are identical",
        "'is' only works for numbers",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "BEGINNER",
      explanation: "'is' checks if two variables refer to the same object (identity), while '==' checks if values are equal.",
      points: 1,
    },
    {
      question_text: "You need to remove duplicates from a list. What's the best approach?",
      options: [
        "Use a set: list(set(my_list))",
        "Use a loop to check each element",
        "Use the remove() method",
        "Use the pop() method",
      ],
      correct_answer: 0,
      question_type: "scenario",
      difficulty: "BEGINNER",
      explanation: "Converting to a set removes duplicates automatically, then converting back to a list gives unique elements.",
      points: 1,
    },
    {
      question_text: "What is a Python decorator?",
      options: [
        "A function that modifies another function",
        "A variable type",
        "A data structure",
        "A loop construct",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "BEGINNER",
      explanation: "A decorator is a function that takes another function and extends its behavior without modifying it explicitly.",
      points: 1,
    },
    // INTERMEDIATE (8 questions)
    {
      question_text: "What is the difference between __str__ and __repr__ in Python?",
      options: [
        "__str__ is for end users, __repr__ is for developers (should be unambiguous)",
        "__repr__ is for end users, __str__ is for developers",
        "They are identical",
        "__str__ only works for strings",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "INTERMEDIATE",
      explanation: "__str__ returns a human-readable string, while __repr__ should return an unambiguous representation for developers.",
      points: 1,
    },
    {
      question_text: "Write a Python function to flatten a nested list.",
      options: [
        "def flatten(lst): return [item for sublist in lst for item in sublist]",
        "def flatten(lst): return lst.flat()",
        "def flatten(lst): return lst.flatten()",
        "def flatten(lst): return list(set(lst))",
      ],
      correct_answer: 0,
      question_type: "practical",
      difficulty: "INTERMEDIATE",
      explanation: "The list comprehension iterates through each sublist and then each item, creating a flat list.",
      points: 1,
    },
    {
      question_text: "What is a generator in Python?",
      options: [
        "A function that returns an iterator using yield",
        "A type of list",
        "A way to create classes",
        "A built-in function",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "INTERMEDIATE",
      explanation: "A generator is a function that uses 'yield' to produce values one at a time, making it memory efficient.",
      points: 1,
    },
    {
      question_text: "What is the Global Interpreter Lock (GIL) in Python?",
      options: [
        "A mechanism that allows only one thread to execute Python bytecode at a time",
        "A way to lock global variables",
        "A type of data structure",
        "A debugging tool",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "INTERMEDIATE",
      explanation: "The GIL is a mutex that prevents multiple native threads from executing Python bytecodes simultaneously.",
      points: 1,
    },
    {
      question_text: "Write a Python function to find the first duplicate in a list.",
      options: [
        "def find_duplicate(lst): seen = set(); for item in lst: if item in seen: return item; seen.add(item); return None",
        "def find_duplicate(lst): return lst[0]",
        "def find_duplicate(lst): return len(lst)",
        "def find_duplicate(lst): return set(lst)",
      ],
      correct_answer: 0,
      question_type: "practical",
      difficulty: "INTERMEDIATE",
      explanation: "Using a set to track seen items allows O(1) lookup to find the first duplicate efficiently.",
      points: 1,
    },
    {
      question_text: "What is the difference between *args and **kwargs in Python?",
      options: [
        "*args is for positional arguments, **kwargs is for keyword arguments",
        "**kwargs is for positional arguments, *args is for keyword arguments",
        "They are identical",
        "*args only works for lists",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "INTERMEDIATE",
      explanation: "*args collects positional arguments into a tuple, while **kwargs collects keyword arguments into a dictionary.",
      points: 1,
    },
    {
      question_text: "You need to process a large file line by line without loading it all into memory. What's the best approach?",
      options: [
        "Use a for loop with open(): for line in open('file.txt'):",
        "Use readlines() to load all lines",
        "Use read() to load entire file",
        "Use pickle to load the file",
      ],
      correct_answer: 0,
      question_type: "scenario",
      difficulty: "INTERMEDIATE",
      explanation: "Iterating over a file object reads one line at a time, making it memory efficient for large files.",
      points: 1,
    },
    {
      question_text: "What is the time complexity of searching in a Python dictionary?",
      options: ["O(n)", "O(log n)", "O(1) average case", "O(n log n)"],
      correct_answer: 2,
      question_type: "conceptual",
      difficulty: "INTERMEDIATE",
      explanation: "Python dictionaries use hash tables, providing O(1) average-case lookup time.",
      points: 1,
    },
    // ADVANCED (4 questions)
    {
      question_text: "What is a context manager in Python and how do you create one?",
      options: [
        "An object that implements __enter__ and __exit__ methods",
        "A type of function",
        "A data structure",
        "A built-in class",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "ADVANCED",
      explanation: "Context managers implement the context manager protocol with __enter__ and __exit__ methods, used with 'with' statements.",
      points: 1,
    },
    {
      question_text: "Write a Python decorator that measures the execution time of a function.",
      options: [
        "import time; def timer(func): def wrapper(*args, **kwargs): start = time.time(); result = func(*args, **kwargs); print(f'Time: {time.time() - start}'); return result; return wrapper",
        "def timer(func): return func",
        "def timer(func): return func()",
        "def timer(func): print('timer')",
      ],
      correct_answer: 0,
      question_type: "practical",
      difficulty: "ADVANCED",
      explanation: "The decorator wraps the function, records start time, executes the function, and prints the elapsed time.",
      points: 1,
    },
    {
      question_text: "You need to implement a thread-safe counter in Python. What's the best approach?",
      options: [
        "Use threading.Lock() to synchronize access",
        "Use a regular variable",
        "Use a list",
        "Use a set",
      ],
      correct_answer: 0,
      question_type: "scenario",
      difficulty: "ADVANCED",
      explanation: "Using a Lock ensures that only one thread can modify the counter at a time, preventing race conditions.",
      points: 1,
    },
    {
      question_text: "What is the difference between __new__ and __init__ in Python?",
      options: [
        "__new__ creates the instance, __init__ initializes it",
        "__init__ creates the instance, __new__ initializes it",
        "They are identical",
        "__new__ only works for classes",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "ADVANCED",
      explanation: "__new__ is called to create a new instance (constructor), while __init__ is called to initialize the instance.",
      points: 1,
    },
  ],
  // Add similar structures for other skills...
  "JavaScript": [
    // BEGINNER (8 questions)
    {
      question_text: "What is the difference between 'let', 'const', and 'var' in JavaScript?",
      options: [
        "'let' and 'const' are block-scoped, 'var' is function-scoped",
        "'var' is block-scoped, 'let' and 'const' are function-scoped",
        "They are all identical",
        "'const' is mutable, 'let' is immutable",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "BEGINNER",
      explanation: "'let' and 'const' are block-scoped (ES6+), while 'var' is function-scoped. 'const' is also immutable.",
      points: 1,
    },
    {
      question_text: "What is a closure in JavaScript?",
      options: [
        "A function that has access to variables in its outer scope",
        "A way to close a function",
        "A type of loop",
        "A data structure",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "BEGINNER",
      explanation: "A closure is a function that retains access to variables from its outer (enclosing) scope even after the outer function has returned.",
      points: 1,
    },
    {
      question_text: "What is the difference between 'null' and 'undefined' in JavaScript?",
      options: [
        "'null' represents the absence of a value, 'undefined' represents an uninitialized variable",
        "'undefined' represents the absence of a value, 'null' represents an uninitialized variable",
        "They are identical",
        "'null' is a primitive, 'undefined' is an object",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "BEGINNER",
      explanation: "'null' is an assigned value meaning 'no value', while 'undefined' means a variable has been declared but not assigned.",
      points: 1,
    },
    {
      question_text: "Write a JavaScript function to check if a string is a palindrome.",
      options: [
        "function isPalindrome(str) { return str === str.split('').reverse().join(''); }",
        "function isPalindrome(str) { return str === str.split('').sort().join(''); }",
        "function isPalindrome(str) { return str.length > 0; }",
        "function isPalindrome(str) { return str === str; }",
      ],
      correct_answer: 0,
      question_type: "practical",
      difficulty: "BEGINNER",
      explanation: "The function splits the string into an array, reverses it, joins it back, and compares with the original.",
      points: 1,
    },
    {
      question_text: "What is the 'this' keyword in JavaScript?",
      options: [
        "It refers to the current execution context",
        "It refers to the global object",
        "It is a variable name",
        "It refers to the parent function",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "BEGINNER",
      explanation: "'this' refers to the object that is executing the current function. Its value depends on how the function is called.",
      points: 1,
    },
    {
      question_text: "What is the difference between '==' and '===' in JavaScript?",
      options: [
        "'==' checks value equality, '===' checks value and type equality",
        "'===' checks value equality, '==' checks value and type equality",
        "They are identical",
        "'==' only works for numbers",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "BEGINNER",
      explanation: "'==' performs type coercion before comparison, while '===' checks both value and type without coercion.",
      points: 1,
    },
    {
      question_text: "You need to add an element to the end of an array. What method should you use?",
      options: ["push()", "pop()", "shift()", "unshift()"],
      correct_answer: 0,
      question_type: "scenario",
      difficulty: "BEGINNER",
      explanation: "push() adds one or more elements to the end of an array and returns the new length.",
      points: 1,
    },
    {
      question_text: "What is an arrow function in JavaScript?",
      options: [
        "A shorter syntax for writing functions with lexical 'this' binding",
        "A type of loop",
        "A data structure",
        "A way to import modules",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "BEGINNER",
      explanation: "Arrow functions provide a concise syntax and automatically bind 'this' to the enclosing scope.",
      points: 1,
    },
    // INTERMEDIATE (8 questions)
    {
      question_text: "What is the purpose of 'async/await' in JavaScript?",
      options: [
        "To handle asynchronous operations in a synchronous-like manner",
        "To make synchronous code asynchronous",
        "To handle errors",
        "To import modules",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "INTERMEDIATE",
      explanation: "async/await allows writing asynchronous code that looks and behaves like synchronous code, making it easier to read and maintain.",
      points: 1,
    },
    {
      question_text: "Write a JavaScript function to debounce another function.",
      options: [
        "function debounce(func, delay) { let timeout; return function(...args) { clearTimeout(timeout); timeout = setTimeout(() => func(...args), delay); }; }",
        "function debounce(func, delay) { return func; }",
        "function debounce(func, delay) { return delay; }",
        "function debounce(func, delay) { return function() { func(); }; }",
      ],
      correct_answer: 0,
      question_type: "practical",
      difficulty: "INTERMEDIATE",
      explanation: "Debounce delays function execution until after a specified time has passed since the last invocation.",
      points: 1,
    },
    {
      question_text: "What is the Event Loop in JavaScript?",
      options: [
        "A mechanism that handles asynchronous operations and manages the call stack",
        "A type of loop",
        "A data structure",
        "A way to handle errors",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "INTERMEDIATE",
      explanation: "The Event Loop continuously checks the call stack and callback queue, moving callbacks to the stack when it's empty.",
      points: 1,
    },
    {
      question_text: "What is a Promise in JavaScript?",
      options: [
        "An object representing the eventual completion or failure of an asynchronous operation",
        "A type of function",
        "A data structure",
        "A way to declare variables",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "INTERMEDIATE",
      explanation: "A Promise is an object that represents a value that may not be available yet, but will be resolved or rejected in the future.",
      points: 1,
    },
    {
      question_text: "Write a JavaScript function to flatten a nested array.",
      options: [
        "function flatten(arr) { return arr.reduce((acc, val) => acc.concat(Array.isArray(val) ? flatten(val) : val), []); }",
        "function flatten(arr) { return arr; }",
        "function flatten(arr) { return arr.length; }",
        "function flatten(arr) { return arr[0]; }",
      ],
      correct_answer: 0,
      question_type: "practical",
      difficulty: "INTERMEDIATE",
      explanation: "The function uses reduce and recursion to flatten nested arrays of any depth.",
      points: 1,
    },
    {
      question_text: "What is the difference between 'map', 'filter', and 'reduce' in JavaScript?",
      options: [
        "'map' transforms elements, 'filter' selects elements, 'reduce' accumulates to a single value",
        "They are identical",
        "'filter' transforms, 'map' selects, 'reduce' filters",
        "'reduce' transforms, 'map' filters, 'filter' reduces",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "INTERMEDIATE",
      explanation: "map() creates a new array with transformed elements, filter() creates a new array with selected elements, reduce() accumulates to a single value.",
      points: 1,
    },
    {
      question_text: "You need to make an API call and handle the response. What's the best modern approach?",
      options: [
        "Use fetch() with async/await",
        "Use XMLHttpRequest",
        "Use jQuery.ajax()",
        "Use document.write()",
      ],
      correct_answer: 0,
      question_type: "scenario",
      difficulty: "INTERMEDIATE",
      explanation: "fetch() with async/await is the modern, promise-based approach for making HTTP requests in JavaScript.",
      points: 1,
    },
    {
      question_text: "What is hoisting in JavaScript?",
      options: [
        "The behavior of moving declarations to the top of their scope",
        "A way to lift variables",
        "A type of function",
        "A data structure",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "INTERMEDIATE",
      explanation: "Hoisting is JavaScript's behavior of moving variable and function declarations to the top of their containing scope during compilation.",
      points: 1,
    },
    // ADVANCED (4 questions)
    {
      question_text: "What is the difference between 'call', 'apply', and 'bind' in JavaScript?",
      options: [
        "'call' and 'apply' invoke immediately with different argument formats, 'bind' returns a new function",
        "They are identical",
        "'bind' invokes immediately, 'call' and 'apply' return functions",
        "'apply' only works for arrays",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "ADVANCED",
      explanation: "'call' takes arguments individually, 'apply' takes an array of arguments, both invoke immediately. 'bind' returns a new function with bound context.",
      points: 1,
    },
    {
      question_text: "Write a JavaScript function to implement a simple memoization cache.",
      options: [
        "function memoize(func) { const cache = {}; return function(...args) { const key = JSON.stringify(args); if(cache[key]) return cache[key]; const result = func(...args); cache[key] = result; return result; }; }",
        "function memoize(func) { return func; }",
        "function memoize(func) { return function() { return func(); }; }",
        "function memoize(func) { return cache; }",
      ],
      correct_answer: 0,
      question_type: "practical",
      difficulty: "ADVANCED",
      explanation: "Memoization caches function results based on input arguments, avoiding redundant calculations.",
      points: 1,
    },
    {
      question_text: "You need to handle multiple asynchronous operations that must complete in order. What's the best approach?",
      options: [
        "Use async/await with sequential await calls",
        "Use Promise.all()",
        "Use setTimeout()",
        "Use a for loop",
      ],
      correct_answer: 0,
      question_type: "scenario",
      difficulty: "ADVANCED",
      explanation: "Sequential await calls ensure operations complete in order, while Promise.all() runs them in parallel.",
      points: 1,
    },
    {
      question_text: "What is a Proxy in JavaScript?",
      options: [
        "An object that wraps another object and intercepts operations",
        "A type of function",
        "A way to make HTTP requests",
        "A data structure",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "ADVANCED",
      explanation: "A Proxy object allows you to create a wrapper for another object and intercept operations like property access, assignment, etc.",
      points: 1,
    },
  ],
  // Continue with other skills - adding placeholder structure
  "Web Development": Array(20).fill(null).map((_, i) => ({
    question_text: `Web Development Question ${i + 1}`,
    options: ["Option A", "Option B", "Option C", "Option D"],
    correct_answer: i % 4,
    question_type: i < 8 ? "conceptual" : i < 16 ? "practical" : "scenario",
    difficulty: i < 8 ? "BEGINNER" : i < 16 ? "INTERMEDIATE" : "ADVANCED",
    explanation: `Explanation for question ${i + 1}`,
    points: 1,
  })),
  "Data Structures & Algorithms": Array(20).fill(null).map((_, i) => ({
    question_text: `DSA Question ${i + 1}`,
    options: ["Option A", "Option B", "Option C", "Option D"],
    correct_answer: i % 4,
    question_type: i < 8 ? "conceptual" : i < 16 ? "practical" : "scenario",
    difficulty: i < 8 ? "BEGINNER" : i < 16 ? "INTERMEDIATE" : "ADVANCED",
    explanation: `Explanation for question ${i + 1}`,
    points: 1,
  })),
  "Database Management Systems": Array(20).fill(null).map((_, i) => ({
    question_text: `Database Question ${i + 1}`,
    options: ["Option A", "Option B", "Option C", "Option D"],
    correct_answer: i % 4,
    question_type: i < 8 ? "conceptual" : i < 16 ? "practical" : "scenario",
    difficulty: i < 8 ? "BEGINNER" : i < 16 ? "INTERMEDIATE" : "ADVANCED",
    explanation: `Explanation for question ${i + 1}`,
    points: 1,
  })),
  "Machine Learning": Array(20).fill(null).map((_, i) => ({
    question_text: `ML Question ${i + 1}`,
    options: ["Option A", "Option B", "Option C", "Option D"],
    correct_answer: i % 4,
    question_type: i < 8 ? "conceptual" : i < 16 ? "practical" : "scenario",
    difficulty: i < 8 ? "BEGINNER" : i < 16 ? "INTERMEDIATE" : "ADVANCED",
    explanation: `Explanation for question ${i + 1}`,
    points: 1,
  })),
  "System Design": Array(20).fill(null).map((_, i) => ({
    question_text: `System Design Question ${i + 1}`,
    options: ["Option A", "Option B", "Option C", "Option D"],
    correct_answer: i % 4,
    question_type: i < 8 ? "conceptual" : i < 16 ? "practical" : "scenario",
    difficulty: i < 8 ? "BEGINNER" : i < 16 ? "INTERMEDIATE" : "ADVANCED",
    explanation: `Explanation for question ${i + 1}`,
    points: 1,
  })),
  "React.js": [
    // BEGINNER (8 questions)
    {
      question_text: "What is React?",
      options: [
        "A JavaScript library for building user interfaces",
        "A database management system",
        "A CSS framework",
        "A server-side framework",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "BEGINNER",
      explanation: "React is a JavaScript library developed by Facebook for building user interfaces, particularly web applications.",
      points: 1,
    },
    {
      question_text: "What is a React component?",
      options: [
        "A reusable piece of code that returns JSX",
        "A database table",
        "A CSS class",
        "A JavaScript function that cannot return anything",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "BEGINNER",
      explanation: "A React component is a reusable piece of code that encapsulates UI logic and returns JSX to render.",
      points: 1,
    },
    {
      question_text: "What is JSX?",
      options: [
        "A syntax extension that allows writing HTML-like code in JavaScript",
        "A database query language",
        "A CSS preprocessor",
        "A package manager",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "BEGINNER",
      explanation: "JSX (JavaScript XML) is a syntax extension that allows you to write HTML-like code in JavaScript.",
      points: 1,
    },
    {
      question_text: "What is the purpose of props in React?",
      options: [
        "To pass data from parent to child components",
        "To store component state",
        "To handle events",
        "To import modules",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "BEGINNER",
      explanation: "Props (properties) are used to pass data from parent components to child components in React.",
      points: 1,
    },
    {
      question_text: "What is state in React?",
      options: [
        "Data that can change over time and triggers re-renders",
        "A static configuration object",
        "A CSS property",
        "A database connection",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "BEGINNER",
      explanation: "State is data that can change over time. When state changes, React re-renders the component.",
      points: 1,
    },
    {
      question_text: "Write a basic React functional component that displays 'Hello World'.",
      options: [
        "function Hello() { return <h1>Hello World</h1>; }",
        "function Hello() { return 'Hello World'; }",
        "function Hello() { console.log('Hello World'); }",
        "const Hello = 'Hello World';",
      ],
      correct_answer: 0,
      question_type: "practical",
      difficulty: "BEGINNER",
      explanation: "A React functional component must return JSX. The correct syntax returns an h1 element with the text.",
      points: 1,
    },
    {
      question_text: "You need to update a component when a user clicks a button. What should you use?",
      options: [
        "useState hook and onClick event handler",
        "props",
        "import statement",
        "CSS classes",
      ],
      correct_answer: 0,
      question_type: "scenario",
      difficulty: "BEGINNER",
      explanation: "To update a component on user interaction, you need useState to manage state and onClick to handle the click event.",
      points: 1,
    },
    {
      question_text: "What does React use to optimize rendering?",
      options: [
        "Virtual DOM",
        "Real DOM directly",
        "CSS animations",
        "Server-side rendering only",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "BEGINNER",
      explanation: "React uses a Virtual DOM to optimize rendering by comparing changes and updating only what's necessary.",
      points: 1,
    },
    // INTERMEDIATE (8 questions)
    {
      question_text: "What is the difference between useState and useEffect hooks?",
      options: [
        "useState manages state, useEffect handles side effects",
        "They are identical",
        "useEffect manages state, useState handles side effects",
        "Both manage state only",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "INTERMEDIATE",
      explanation: "useState is for managing component state, while useEffect is for handling side effects like API calls, subscriptions, etc.",
      points: 1,
    },
    {
      question_text: "Write a React component that increments a counter when a button is clicked.",
      options: [
        "function Counter() { const [count, setCount] = useState(0); return (<div><p>{count}</p><button onClick={() => setCount(count + 1)}>Increment</button></div>); }",
        "function Counter() { let count = 0; return <button onClick={() => count++}>Increment</button>; }",
        "function Counter() { return <button>Increment</button>; }",
        "const Counter = () => count++;",
      ],
      correct_answer: 0,
      question_type: "practical",
      difficulty: "INTERMEDIATE",
      explanation: "The correct solution uses useState to manage the counter state and updates it with setCount when the button is clicked.",
      points: 1,
    },
    {
      question_text: "What is the purpose of the dependency array in useEffect?",
      options: [
        "To control when the effect runs based on value changes",
        "To import dependencies",
        "To define CSS classes",
        "To store component props",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "INTERMEDIATE",
      explanation: "The dependency array in useEffect determines when the effect should re-run. Empty array means run once, values mean run when they change.",
      points: 1,
    },
    {
      question_text: "What is the difference between controlled and uncontrolled components?",
      options: [
        "Controlled components have React managing their state, uncontrolled use DOM directly",
        "They are identical",
        "Controlled components are faster",
        "Uncontrolled components use hooks",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "INTERMEDIATE",
      explanation: "Controlled components have their value controlled by React state, while uncontrolled components use refs to access DOM directly.",
      points: 1,
    },
    {
      question_text: "Write a React component that fetches and displays data from an API using useEffect.",
      options: [
        "function DataDisplay() { const [data, setData] = useState(null); useEffect(() => { fetch('/api/data').then(r => r.json()).then(setData); }, []); return <div>{data}</div>; }",
        "function DataDisplay() { const data = fetch('/api/data'); return <div>{data}</div>; }",
        "function DataDisplay() { return <div>Data</div>; }",
        "const DataDisplay = 'data';",
      ],
      correct_answer: 0,
      question_type: "practical",
      difficulty: "INTERMEDIATE",
      explanation: "The correct solution uses useState to store data, useEffect to fetch it on mount (empty dependency array), and displays it.",
      points: 1,
    },
    {
      question_text: "What is React.memo used for?",
      options: [
        "To prevent unnecessary re-renders of functional components",
        "To create memoized values",
        "To manage state",
        "To handle events",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "INTERMEDIATE",
      explanation: "React.memo is a higher-order component that memoizes a component, preventing re-renders if props haven't changed.",
      points: 1,
    },
    {
      question_text: "You need to share state between multiple components. What's the best approach?",
      options: [
        "Lift state up to a common parent component",
        "Use global variables",
        "Use CSS variables",
        "Create separate state in each component",
      ],
      correct_answer: 0,
      question_type: "scenario",
      difficulty: "INTERMEDIATE",
      explanation: "Lifting state up to a common parent allows multiple child components to share and update the same state.",
      points: 1,
    },
    {
      question_text: "What is the purpose of keys in React lists?",
      options: [
        "To help React identify which items have changed, been added, or removed",
        "To style list items",
        "To sort the list",
        "To filter the list",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "INTERMEDIATE",
      explanation: "Keys help React efficiently update the UI by identifying which items in a list have changed.",
      points: 1,
    },
    // ADVANCED (4 questions)
    {
      question_text: "What is the difference between useCallback and useMemo?",
      options: [
        "useCallback memoizes functions, useMemo memoizes values",
        "They are identical",
        "useMemo memoizes functions, useCallback memoizes values",
        "Both memoize components",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "ADVANCED",
      explanation: "useCallback returns a memoized callback function, while useMemo returns a memoized value.",
      points: 1,
    },
    {
      question_text: "Write a custom React hook that manages a toggle state.",
      options: [
        "function useToggle(initial = false) { const [state, setState] = useState(initial); const toggle = () => setState(!state); return [state, toggle]; }",
        "function useToggle() { return true; }",
        "function useToggle() { const state = false; return state; }",
        "const useToggle = () => {};",
      ],
      correct_answer: 0,
      question_type: "practical",
      difficulty: "ADVANCED",
      explanation: "A custom hook uses useState internally and returns both the state and a function to toggle it.",
      points: 1,
    },
    {
      question_text: "You need to optimize a component that receives large props and re-renders frequently. What should you use?",
      options: [
        "React.memo with a custom comparison function",
        "useState",
        "useEffect",
        "Inline styles",
      ],
      correct_answer: 0,
      question_type: "scenario",
      difficulty: "ADVANCED",
      explanation: "React.memo can prevent re-renders, and a custom comparison function allows fine-grained control over when to re-render.",
      points: 1,
    },
    {
      question_text: "What is the Context API used for in React?",
      options: [
        "To share data across the component tree without prop drilling",
        "To manage component state",
        "To handle events",
        "To import modules",
      ],
      correct_answer: 0,
      question_type: "conceptual",
      difficulty: "ADVANCED",
      explanation: "Context API allows you to share data through the component tree without passing props down manually at every level.",
      points: 1,
    },
  ],
  "Backend Development": Array(20).fill(null).map((_, i) => ({
    question_text: `Backend Question ${i + 1}`,
    options: ["Option A", "Option B", "Option C", "Option D"],
    correct_answer: i % 4,
    question_type: i < 8 ? "conceptual" : i < 16 ? "practical" : "scenario",
    difficulty: i < 8 ? "BEGINNER" : i < 16 ? "INTERMEDIATE" : "ADVANCED",
    explanation: `Explanation for question ${i + 1}`,
    points: 1,
  })),
};

async function seedSkillTests() {
  console.log("🌱 Seeding skill tests...");

  for (const skill of skills) {
    // Create or get course
    let course = await prisma.courses.findUnique({
      where: { title: skill.title },
    });

    if (!course) {
      course = await prisma.courses.create({
        data: {
          title: skill.title,
          description: skill.description,
          is_active: true,
          career_id: null,
          created_by: "SYSTEM",
        },
      });
      console.log(`✅ Created course: ${skill.title}`);
    } else {
      console.log(`ℹ️  Course already exists: ${skill.title}`);
    }

    // Get questions for this skill
    const questions = questionsBySkill[skill.title] || [];

    if (questions.length === 0) {
      console.log(`⚠️  No questions defined for ${skill.title}`);
      continue;
    }

    // Check if questions already exist
    const existingCount = await prisma.skill_test_questions.count({
      where: { course_id: course.id },
    });

    if (existingCount > 0) {
      console.log(`ℹ️  Questions already exist for ${skill.title} (${existingCount} questions)`);
      continue;
    }

    // Create questions
    const questionsToCreate = questions.map((q) => ({
      course_id: course.id,
      question_text: q.question_text,
      options: q.options,
      correct_answer: q.correct_answer,
      question_type: q.question_type,
      difficulty: q.difficulty,
      explanation: q.explanation,
      points: q.points,
    }));

    await prisma.skill_test_questions.createMany({
      data: questionsToCreate,
    });

    console.log(`✅ Created ${questionsToCreate.length} questions for ${skill.title}`);
  }

  console.log("✨ Skill test seeding completed!");
}

seedSkillTests()
  .catch((e) => {
    console.error("❌ Error seeding skill tests:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
