import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// Topic definitions for each skill
const skillTopics: Record<string, {
  basic: Array<{ week: number; session: number; title: string }>;
  standard: Array<{ week: number; session: number; title: string }>;
  pro: Array<{ week: number; session: number; title: string }>;
}> = {
  "Android Development": {
    basic: [
      { week: 1, session: 1, title: "Introduction to Android Development" },
      { week: 1, session: 2, title: "Android Studio Setup and Project Structure" },
      { week: 1, session: 3, title: "Activities and Lifecycle" },
      { week: 1, session: 4, title: "Layouts and Views" },
      { week: 1, session: 5, title: "Practice Session" },
      { week: 2, session: 1, title: "User Input and Events" },
      { week: 2, session: 2, title: "Intents and Navigation" },
      { week: 2, session: 3, title: "Fragments Basics" },
      { week: 2, session: 4, title: "RecyclerView and Lists" },
      { week: 2, session: 5, title: "Practice Session" },
      { week: 3, session: 1, title: "SharedPreferences and Data Storage" },
      { week: 3, session: 2, title: "SQLite Database" },
      { week: 3, session: 3, title: "Room Database Basics" },
      { week: 3, session: 4, title: "File Storage" },
      { week: 3, session: 5, title: "Practice Session" },
      { week: 4, session: 1, title: "Networking with Retrofit" },
      { week: 4, session: 2, title: "REST API Integration" },
      { week: 4, session: 3, title: "JSON Parsing" },
      { week: 4, session: 4, title: "Error Handling" },
      { week: 4, session: 5, title: "Final Project Review" },
    ],
    standard: [
      { week: 1, session: 1, title: "Advanced Android Architecture" },
      { week: 1, session: 2, title: "MVVM Pattern" },
      { week: 1, session: 3, title: "LiveData and ViewModel" },
      { week: 1, session: 4, title: "Data Binding" },
      { week: 1, session: 5, title: "Practice Session" },
      { week: 2, session: 1, title: "Dependency Injection with Dagger/Hilt" },
      { week: 2, session: 2, title: "Coroutines and Flow" },
      { week: 2, session: 3, title: "Async Operations" },
      { week: 2, session: 4, title: "Background Tasks" },
      { week: 2, session: 5, title: "Practice Session" },
      { week: 3, session: 1, title: "Room Database Advanced" },
      { week: 3, session: 2, title: "Database Migrations" },
      { week: 3, session: 3, title: "WorkManager" },
      { week: 3, session: 4, title: "Notifications" },
      { week: 3, session: 5, title: "Practice Session" },
      { week: 4, session: 1, title: "Material Design Components" },
      { week: 4, session: 2, title: "Custom Views" },
      { week: 4, session: 3, title: "Animations" },
      { week: 4, session: 4, title: "Theming and Styles" },
      { week: 4, session: 5, title: "Practice Session" },
      { week: 5, session: 1, title: "Firebase Integration" },
      { week: 5, session: 2, title: "Firebase Authentication" },
      { week: 5, session: 3, title: "Cloud Firestore" },
      { week: 5, session: 4, title: "Firebase Storage" },
      { week: 5, session: 5, title: "Practice Session" },
      { week: 6, session: 1, title: "Testing Strategies" },
      { week: 6, session: 2, title: "Unit Testing" },
      { week: 6, session: 3, title: "UI Testing with Espresso" },
      { week: 6, session: 4, title: "Mocking and Test Doubles" },
      { week: 6, session: 5, title: "Practice Session" },
      { week: 7, session: 1, title: "Performance Optimization" },
      { week: 7, session: 2, title: "Memory Management" },
      { week: 7, session: 3, title: "Proguard and R8" },
      { week: 7, session: 4, title: "App Size Optimization" },
      { week: 7, session: 5, title: "Practice Session" },
      { week: 8, session: 1, title: "Publishing to Play Store" },
      { week: 8, session: 2, title: "App Signing" },
      { week: 8, session: 3, title: "Version Management" },
      { week: 8, session: 4, title: "Analytics and Monitoring" },
      { week: 8, session: 5, title: "Final Project Review" },
    ],
    pro: [
      { week: 1, session: 1, title: "Advanced Architecture Patterns" },
      { week: 1, session: 2, title: "Clean Architecture" },
      { week: 1, session: 3, title: "MVI Pattern" },
      { week: 1, session: 4, title: "Modular Architecture" },
      { week: 1, session: 5, title: "Architecture Best Practices" },
      { week: 2, session: 1, title: "Advanced Kotlin Features" },
      { week: 2, session: 2, title: "Kotlin Coroutines Deep Dive" },
      { week: 2, session: 3, title: "Flow and StateFlow" },
      { week: 2, session: 4, title: "Kotlin Multiplatform" },
      { week: 2, session: 5, title: "Kotlin Best Practices" },
      { week: 3, session: 1, title: "Jetpack Compose Fundamentals" },
      { week: 3, session: 2, title: "Compose State Management" },
      { week: 3, session: 3, title: "Compose Navigation" },
      { week: 3, session: 4, title: "Custom Composables" },
      { week: 3, session: 5, title: "Compose Best Practices" },
      { week: 4, session: 1, title: "Advanced UI Components" },
      { week: 4, session: 2, title: "Custom ViewGroups" },
      { week: 4, session: 3, title: "Canvas and Custom Drawing" },
      { week: 4, session: 4, title: "Advanced Animations" },
      { week: 4, session: 5, title: "UI Performance Optimization" },
      { week: 5, session: 1, title: "Advanced Networking" },
      { week: 5, session: 2, title: "GraphQL with Apollo" },
      { week: 5, session: 3, title: "WebSocket Integration" },
      { week: 5, session: 4, title: "Offline-First Architecture" },
      { week: 5, session: 5, title: "Network Best Practices" },
      { week: 6, session: 1, title: "Advanced Database Patterns" },
      { week: 6, session: 2, title: "Database Relationships" },
      { week: 6, session: 3, title: "Complex Queries" },
      { week: 6, session: 4, title: "Database Optimization" },
      { week: 6, session: 5, title: "Data Persistence Strategies" },
      { week: 7, session: 1, title: "Security Best Practices" },
      { week: 7, session: 2, title: "Encryption and Key Management" },
      { week: 7, session: 3, title: "Secure Communication" },
      { week: 7, session: 4, title: "Obfuscation and Anti-Tampering" },
      { week: 7, session: 5, title: "Security Audit" },
      { week: 8, session: 1, title: "Advanced Testing" },
      { week: 8, session: 2, title: "Integration Testing" },
      { week: 8, session: 3, title: "Snapshot Testing" },
      { week: 8, session: 4, title: "Test Automation" },
      { week: 8, session: 5, title: "Testing Best Practices" },
      { week: 9, session: 1, title: "CI/CD for Android" },
      { week: 9, session: 2, title: "GitHub Actions" },
      { week: 9, session: 3, title: "Fastlane Automation" },
      { week: 9, session: 4, title: "Automated Testing Pipeline" },
      { week: 9, session: 5, title: "DevOps Best Practices" },
      { week: 10, session: 1, title: "Performance Profiling" },
      { week: 10, session: 2, title: "Memory Leak Detection" },
      { week: 10, session: 3, title: "CPU and Battery Optimization" },
      { week: 10, session: 4, title: "Network Optimization" },
      { week: 10, session: 5, title: "Performance Best Practices" },
      { week: 11, session: 1, title: "Advanced Firebase Features" },
      { week: 11, session: 2, title: "Cloud Functions" },
      { week: 11, session: 3, title: "Remote Config" },
      { week: 11, session: 4, title: "Crashlytics and Analytics" },
      { week: 11, session: 5, title: "Firebase Best Practices" },
      { week: 12, session: 1, title: "Enterprise App Development" },
      { week: 12, session: 2, title: "Multi-Module Projects" },
      { week: 12, session: 3, title: "Code Review and Refactoring" },
      { week: 12, session: 4, title: "Project Architecture Review" },
      { week: 12, session: 5, title: "Career Guidance" },
    ],
  },
  "Data Structures": {
    basic: [
      { week: 1, session: 1, title: "Introduction to Data Structures" },
      { week: 1, session: 2, title: "Arrays and Dynamic Arrays" },
      { week: 1, session: 3, title: "Linked Lists - Singly Linked" },
      { week: 1, session: 4, title: "Linked Lists - Doubly Linked" },
      { week: 1, session: 5, title: "Practice Session" },
      { week: 2, session: 1, title: "Stacks - Implementation" },
      { week: 2, session: 2, title: "Queues - Implementation" },
      { week: 2, session: 3, title: "Stack and Queue Applications" },
      { week: 2, session: 4, title: "Deque (Double-ended Queue)" },
      { week: 2, session: 5, title: "Practice Session" },
      { week: 3, session: 1, title: "Trees - Binary Trees" },
      { week: 3, session: 2, title: "Binary Search Trees (BST)" },
      { week: 3, session: 3, title: "Tree Traversals" },
      { week: 3, session: 4, title: "BST Operations" },
      { week: 3, session: 5, title: "Practice Session" },
      { week: 4, session: 1, title: "Hash Tables - Introduction" },
      { week: 4, session: 2, title: "Hash Functions" },
      { week: 4, session: 3, title: "Collision Resolution" },
      { week: 4, session: 4, title: "Hash Table Applications" },
      { week: 4, session: 5, title: "Final Project Review" },
    ],
    standard: [
      { week: 1, session: 1, title: "Advanced Trees - AVL Trees" },
      { week: 1, session: 2, title: "AVL Tree Rotations" },
      { week: 1, session: 3, title: "Red-Black Trees" },
      { week: 1, session: 4, title: "B-Trees and B+ Trees" },
      { week: 1, session: 5, title: "Practice Session" },
      { week: 2, session: 1, title: "Heaps - Min and Max Heaps" },
      { week: 2, session: 2, title: "Heap Operations" },
      { week: 2, session: 3, title: "Priority Queues" },
      { week: 2, session: 4, title: "Heap Sort Algorithm" },
      { week: 2, session: 5, title: "Practice Session" },
      { week: 3, session: 1, title: "Graphs - Introduction" },
      { week: 3, session: 2, title: "Graph Representation" },
      { week: 3, session: 3, title: "BFS (Breadth-First Search)" },
      { week: 3, session: 4, title: "DFS (Depth-First Search)" },
      { week: 3, session: 5, title: "Practice Session" },
      { week: 4, session: 1, title: "Shortest Path Algorithms" },
      { week: 4, session: 2, title: "Dijkstra's Algorithm" },
      { week: 4, session: 3, title: "Bellman-Ford Algorithm" },
      { week: 4, session: 4, title: "Floyd-Warshall Algorithm" },
      { week: 4, session: 5, title: "Practice Session" },
      { week: 5, session: 1, title: "Minimum Spanning Tree" },
      { week: 5, session: 2, title: "Kruskal's Algorithm" },
      { week: 5, session: 3, title: "Prim's Algorithm" },
      { week: 5, session: 4, title: "Union-Find Data Structure" },
      { week: 5, session: 5, title: "Practice Session" },
      { week: 6, session: 1, title: "Advanced Hash Tables" },
      { week: 6, session: 2, title: "Open Addressing" },
      { week: 6, session: 3, title: "Chaining Strategies" },
      { week: 6, session: 4, title: "Hash Table Optimization" },
      { week: 6, session: 5, title: "Practice Session" },
      { week: 7, session: 1, title: "Trie Data Structure" },
      { week: 7, session: 2, title: "Trie Operations" },
      { week: 7, session: 3, title: "Suffix Trees" },
      { week: 7, session: 4, title: "Advanced String Algorithms" },
      { week: 7, session: 5, title: "Practice Session" },
      { week: 8, session: 1, title: "Time Complexity Analysis" },
      { week: 8, session: 2, title: "Space Complexity" },
      { week: 8, session: 3, title: "Amortized Analysis" },
      { week: 8, session: 4, title: "Problem Solving Strategies" },
      { week: 8, session: 5, title: "Final Project Review" },
    ],
    pro: [
      { week: 1, session: 1, title: "Advanced Tree Structures" },
      { week: 1, session: 2, title: "Segment Trees" },
      { week: 1, session: 3, title: "Fenwick Trees (Binary Indexed Trees)" },
      { week: 1, session: 4, title: "Splay Trees" },
      { week: 1, session: 5, title: "Advanced Tree Applications" },
      { week: 2, session: 1, title: "Advanced Graph Algorithms" },
      { week: 2, session: 2, title: "Topological Sort" },
      { week: 2, session: 3, title: "Strongly Connected Components" },
      { week: 2, session: 4, title: "Articulation Points and Bridges" },
      { week: 2, session: 5, title: "Graph Algorithm Optimization" },
      { week: 3, session: 1, title: "Dynamic Programming Fundamentals" },
      { week: 3, session: 2, title: "DP Patterns and Strategies" },
      { week: 3, session: 3, title: "Memoization vs Tabulation" },
      { week: 3, session: 4, title: "Advanced DP Problems" },
      { week: 3, session: 5, title: "DP Best Practices" },
      { week: 4, session: 1, title: "Greedy Algorithms" },
      { week: 4, session: 2, title: "Greedy Strategy Design" },
      { week: 4, session: 3, title: "Activity Selection Problems" },
      { week: 4, session: 4, title: "Huffman Coding" },
      { week: 4, session: 5, title: "Greedy Algorithm Applications" },
      { week: 5, session: 1, title: "Advanced Sorting Algorithms" },
      { week: 5, session: 2, title: "Quick Sort Optimization" },
      { week: 5, session: 3, title: "Merge Sort Variants" },
      { week: 5, session: 4, title: "Radix Sort and Counting Sort" },
      { week: 5, session: 5, title: "Sorting Algorithm Comparison" },
      { week: 6, session: 1, title: "String Matching Algorithms" },
      { week: 6, session: 2, title: "KMP Algorithm" },
      { week: 6, session: 3, title: "Rabin-Karp Algorithm" },
      { week: 6, session: 4, title: "Boyer-Moore Algorithm" },
      { week: 6, session: 5, title: "String Algorithm Applications" },
      { week: 7, session: 1, title: "Advanced Data Structures" },
      { week: 7, session: 2, title: "Skip Lists" },
      { week: 7, session: 3, title: "Bloom Filters" },
      { week: 7, session: 4, title: "Disjoint Set Union" },
      { week: 7, session: 5, title: "Specialized Data Structures" },
      { week: 8, session: 1, title: "Competitive Programming Patterns" },
      { week: 8, session: 2, title: "Two Pointers Technique" },
      { week: 8, session: 3, title: "Sliding Window" },
      { week: 8, session: 4, title: "Binary Search on Answer" },
      { week: 8, session: 5, title: "Problem Solving Techniques" },
      { week: 9, session: 1, title: "Advanced Graph Problems" },
      { week: 9, session: 2, title: "Network Flow Algorithms" },
      { week: 9, session: 3, title: "Maximum Flow" },
      { week: 9, session: 4, title: "Minimum Cost Flow" },
      { week: 9, session: 5, title: "Graph Theory Applications" },
      { week: 10, session: 1, title: "Backtracking Algorithms" },
      { week: 10, session: 2, title: "N-Queens Problem" },
      { week: 10, session: 3, title: "Sudoku Solver" },
      { week: 10, session: 4, title: "Constraint Satisfaction" },
      { week: 10, session: 5, title: "Backtracking Optimization" },
      { week: 11, session: 1, title: "Advanced Optimization" },
      { week: 11, session: 2, title: "Space-Time Tradeoffs" },
      { week: 11, session: 3, title: "Cache-Optimal Algorithms" },
      { week: 11, session: 4, title: "Parallel Algorithms" },
      { week: 11, session: 5, title: "Performance Optimization" },
      { week: 12, session: 1, title: "System Design with Data Structures" },
      { week: 12, session: 2, title: "Real-World Applications" },
      { week: 12, session: 3, title: "Code Review and Optimization" },
      { week: 12, session: 4, title: "Interview Preparation" },
      { week: 12, session: 5, title: "Career Guidance" },
    ],
  },
  "Machine Learning": {
    basic: [
      { week: 1, session: 1, title: "Introduction to Machine Learning" },
      { week: 1, session: 2, title: "Python for ML - NumPy Basics" },
      { week: 1, session: 3, title: "Pandas for Data Manipulation" },
      { week: 1, session: 4, title: "Data Visualization with Matplotlib" },
      { week: 1, session: 5, title: "Practice Session" },
      { week: 2, session: 1, title: "Supervised Learning Basics" },
      { week: 2, session: 2, title: "Linear Regression" },
      { week: 2, session: 3, title: "Logistic Regression" },
      { week: 2, session: 4, title: "Model Evaluation Metrics" },
      { week: 2, session: 5, title: "Practice Session" },
      { week: 3, session: 1, title: "Data Preprocessing" },
      { week: 3, session: 2, title: "Feature Scaling and Normalization" },
      { week: 3, session: 3, title: "Handling Missing Data" },
      { week: 3, session: 4, title: "Feature Engineering" },
      { week: 3, session: 5, title: "Practice Session" },
      { week: 4, session: 1, title: "Classification Algorithms" },
      { week: 4, session: 2, title: "K-Nearest Neighbors (KNN)" },
      { week: 4, session: 3, title: "Decision Trees" },
      { week: 4, session: 4, title: "Model Validation" },
      { week: 4, session: 5, title: "Final Project Review" },
    ],
    standard: [
      { week: 1, session: 1, title: "Advanced Regression Techniques" },
      { week: 1, session: 2, title: "Polynomial Regression" },
      { week: 1, session: 3, title: "Ridge and Lasso Regression" },
      { week: 1, session: 4, title: "Regularization Techniques" },
      { week: 1, session: 5, title: "Practice Session" },
      { week: 2, session: 1, title: "Ensemble Methods" },
      { week: 2, session: 2, title: "Random Forest" },
      { week: 2, session: 3, title: "Gradient Boosting" },
      { week: 2, session: 4, title: "XGBoost and LightGBM" },
      { week: 2, session: 5, title: "Practice Session" },
      { week: 3, session: 1, title: "Support Vector Machines (SVM)" },
      { week: 3, session: 2, title: "Kernel Methods" },
      { week: 3, session: 3, title: "SVM for Classification" },
      { week: 3, session: 4, title: "SVM for Regression" },
      { week: 3, session: 5, title: "Practice Session" },
      { week: 4, session: 1, title: "Unsupervised Learning" },
      { week: 4, session: 2, title: "K-Means Clustering" },
      { week: 4, session: 3, title: "Hierarchical Clustering" },
      { week: 4, session: 4, title: "DBSCAN Clustering" },
      { week: 4, session: 5, title: "Practice Session" },
      { week: 5, session: 1, title: "Dimensionality Reduction" },
      { week: 5, session: 2, title: "Principal Component Analysis (PCA)" },
      { week: 5, session: 3, title: "t-SNE and UMAP" },
      { week: 5, session: 4, title: "Feature Selection" },
      { week: 5, session: 5, title: "Practice Session" },
      { week: 6, session: 1, title: "Neural Networks Introduction" },
      { week: 6, session: 2, title: "Perceptrons and Activation Functions" },
      { week: 6, session: 3, title: "Backpropagation" },
      { week: 6, session: 4, title: "Multi-layer Perceptrons" },
      { week: 6, session: 5, title: "Practice Session" },
      { week: 7, session: 1, title: "Model Selection and Hyperparameter Tuning" },
      { week: 7, session: 2, title: "Cross-Validation" },
      { week: 7, session: 3, title: "Grid Search and Random Search" },
      { week: 7, session: 4, title: "Bayesian Optimization" },
      { week: 7, session: 5, title: "Practice Session" },
      { week: 8, session: 1, title: "ML Project Workflow" },
      { week: 8, session: 2, title: "End-to-End ML Pipeline" },
      { week: 8, session: 3, title: "Model Deployment Basics" },
      { week: 8, session: 4, title: "ML Best Practices" },
      { week: 8, session: 5, title: "Final Project Review" },
    ],
    pro: [
      { week: 1, session: 1, title: "Deep Learning Fundamentals" },
      { week: 1, session: 2, title: "TensorFlow and Keras" },
      { week: 1, session: 3, title: "PyTorch Basics" },
      { week: 1, session: 4, title: "Neural Network Architectures" },
      { week: 1, session: 5, title: "Deep Learning Best Practices" },
      { week: 2, session: 1, title: "Convolutional Neural Networks (CNN)" },
      { week: 2, session: 2, title: "CNN Architectures" },
      { week: 2, session: 3, title: "Transfer Learning" },
      { week: 2, session: 4, title: "Image Classification" },
      { week: 2, session: 5, title: "CNN Applications" },
      { week: 3, session: 1, title: "Recurrent Neural Networks (RNN)" },
      { week: 3, session: 2, title: "LSTM and GRU" },
      { week: 3, session: 3, title: "Sequence-to-Sequence Models" },
      { week: 3, session: 4, title: "Attention Mechanisms" },
      { week: 3, session: 5, title: "RNN Applications" },
      { week: 4, session: 1, title: "Transformers and BERT" },
      { week: 4, session: 2, title: "Transformer Architecture" },
      { week: 4, session: 3, title: "BERT and GPT Models" },
      { week: 4, session: 4, title: "Fine-tuning Pre-trained Models" },
      { week: 4, session: 5, title: "NLP with Transformers" },
      { week: 5, session: 1, title: "Advanced Optimization" },
      { week: 5, session: 2, title: "Adam and Advanced Optimizers" },
      { week: 5, session: 3, title: "Learning Rate Scheduling" },
      { week: 5, session: 4, title: "Batch Normalization" },
      { week: 5, session: 5, title: "Training Optimization" },
      { week: 6, session: 1, title: "Computer Vision Advanced" },
      { week: 6, session: 2, title: "Object Detection" },
      { week: 6, session: 3, title: "YOLO and R-CNN" },
      { week: 6, session: 4, title: "Semantic Segmentation" },
      { week: 6, session: 5, title: "CV Applications" },
      { week: 7, session: 1, title: "Natural Language Processing" },
      { week: 7, session: 2, title: "Text Preprocessing" },
      { week: 7, session: 3, title: "Word Embeddings" },
      { week: 7, session: 4, title: "Sentiment Analysis" },
      { week: 7, session: 5, title: "NLP Applications" },
      { week: 8, session: 1, title: "Reinforcement Learning Basics" },
      { week: 8, session: 2, title: "Q-Learning" },
      { week: 8, session: 3, title: "Deep Q-Networks (DQN)" },
      { week: 8, session: 4, title: "Policy Gradient Methods" },
      { week: 8, session: 5, title: "RL Applications" },
      { week: 9, session: 1, title: "MLOps and Production" },
      { week: 9, session: 2, title: "Model Versioning" },
      { week: 9, session: 3, title: "ML Pipeline Automation" },
      { week: 9, session: 4, title: "Model Monitoring" },
      { week: 9, session: 5, title: "MLOps Best Practices" },
      { week: 10, session: 1, title: "Advanced Topics" },
      { week: 10, session: 2, title: "Generative Adversarial Networks (GANs)" },
      { week: 10, session: 3, title: "Variational Autoencoders (VAE)" },
      { week: 10, session: 4, title: "AutoML" },
      { week: 10, session: 5, title: "Advanced ML Techniques" },
      { week: 11, session: 1, title: "ML System Design" },
      { week: 11, session: 2, title: "Scalable ML Systems" },
      { week: 11, session: 3, title: "Distributed Training" },
      { week: 11, session: 4, title: "Model Serving" },
      { week: 11, session: 5, title: "Production ML Systems" },
      { week: 12, session: 1, title: "Ethics in ML" },
      { week: 12, session: 2, title: "Bias and Fairness" },
      { week: 12, session: 3, title: "Explainable AI" },
      { week: 12, session: 4, title: "ML Research Trends" },
      { week: 12, session: 5, title: "Career Guidance" },
    ],
  },
  "System Design": {
    basic: [
      { week: 1, session: 1, title: "Introduction to System Design" },
      { week: 1, session: 2, title: "Scalability Concepts" },
      { week: 1, session: 3, title: "Load Balancing" },
      { week: 1, session: 4, title: "Caching Strategies" },
      { week: 1, session: 5, title: "Practice Session" },
      { week: 2, session: 1, title: "Database Design" },
      { week: 2, session: 2, title: "SQL vs NoSQL" },
      { week: 2, session: 3, title: "Database Sharding" },
      { week: 2, session: 4, title: "Replication and Consistency" },
      { week: 2, session: 5, title: "Practice Session" },
      { week: 3, session: 1, title: "API Design" },
      { week: 3, session: 2, title: "RESTful APIs" },
      { week: 3, session: 3, title: "GraphQL Basics" },
      { week: 3, session: 4, title: "API Versioning" },
      { week: 3, session: 5, title: "Practice Session" },
      { week: 4, session: 1, title: "Message Queues" },
      { week: 4, session: 2, title: "Pub/Sub Patterns" },
      { week: 4, session: 3, title: "Event-Driven Architecture" },
      { week: 4, session: 4, title: "System Design Basics" },
      { week: 4, session: 5, title: "Final Project Review" },
    ],
    standard: [
      { week: 1, session: 1, title: "Advanced Scalability Patterns" },
      { week: 1, session: 2, title: "Horizontal vs Vertical Scaling" },
      { week: 1, session: 3, title: "Microservices Architecture" },
      { week: 1, session: 4, title: "Service Communication" },
      { week: 1, session: 5, title: "Practice Session" },
      { week: 2, session: 1, title: "Distributed Systems" },
      { week: 2, session: 2, title: "CAP Theorem" },
      { week: 2, session: 3, title: "Consistency Models" },
      { week: 2, session: 4, title: "Distributed Transactions" },
      { week: 2, session: 5, title: "Practice Session" },
      { week: 3, session: 1, title: "Advanced Database Patterns" },
      { week: 3, session: 2, title: "Read Replicas" },
      { week: 3, session: 3, title: "Database Partitioning" },
      { week: 3, session: 4, title: "Event Sourcing" },
      { week: 3, session: 5, title: "Practice Session" },
      { week: 4, session: 1, title: "Caching Strategies Advanced" },
      { week: 4, session: 2, title: "Redis and Memcached" },
      { week: 4, session: 3, title: "CDN and Edge Caching" },
      { week: 4, session: 4, title: "Cache Invalidation" },
      { week: 4, session: 5, title: "Practice Session" },
      { week: 5, session: 1, title: "Message Brokers" },
      { week: 5, session: 2, title: "Kafka Fundamentals" },
      { week: 5, session: 3, title: "RabbitMQ" },
      { week: 5, session: 4, title: "Message Queue Patterns" },
      { week: 5, session: 5, title: "Practice Session" },
      { week: 6, session: 1, title: "Search Systems" },
      { week: 6, session: 2, title: "Elasticsearch Basics" },
      { week: 6, session: 3, title: "Full-Text Search" },
      { week: 6, session: 4, title: "Search Optimization" },
      { week: 6, session: 5, title: "Practice Session" },
      { week: 7, session: 1, title: "Monitoring and Observability" },
      { week: 7, session: 2, title: "Logging Strategies" },
      { week: 7, session: 3, title: "Metrics and Tracing" },
      { week: 7, session: 4, title: "Alerting Systems" },
      { week: 7, session: 5, title: "Practice Session" },
      { week: 8, session: 1, title: "System Design Patterns" },
      { week: 8, session: 2, title: "Designing Real Systems" },
      { week: 8, session: 3, title: "Trade-offs Analysis" },
      { week: 8, session: 4, title: "System Design Best Practices" },
      { week: 8, session: 5, title: "Final Project Review" },
    ],
    pro: [
      { week: 1, session: 1, title: "Enterprise System Architecture" },
      { week: 1, session: 2, title: "Domain-Driven Design" },
      { week: 1, session: 3, title: "Hexagonal Architecture" },
      { week: 1, session: 4, title: "Clean Architecture" },
      { week: 1, session: 5, title: "Architecture Patterns" },
      { week: 2, session: 1, title: "Advanced Microservices" },
      { week: 2, session: 2, title: "Service Mesh" },
      { week: 2, session: 3, title: "API Gateway Patterns" },
      { week: 2, session: 4, title: "Circuit Breaker Pattern" },
      { week: 2, session: 5, title: "Microservices Best Practices" },
      { week: 3, session: 1, title: "Distributed Data Management" },
      { week: 3, session: 2, title: "Distributed Consensus" },
      { week: 3, session: 3, title: "Raft Algorithm" },
      { week: 3, session: 4, title: "Paxos Algorithm" },
      { week: 3, session: 5, title: "Consensus Algorithms" },
      { week: 4, session: 1, title: "Advanced Database Systems" },
      { week: 4, session: 2, title: "Time-Series Databases" },
      { week: 4, session: 3, title: "Graph Databases" },
      { week: 4, session: 4, title: "NewSQL Databases" },
      { week: 4, session: 5, title: "Database Selection" },
      { week: 5, session: 1, title: "High-Performance Systems" },
      { week: 5, session: 2, title: "Performance Optimization" },
      { week: 5, session: 3, title: "Latency Optimization" },
      { week: 5, session: 4, title: "Throughput Optimization" },
      { week: 5, session: 5, title: "Performance Best Practices" },
      { week: 6, session: 1, title: "Security in System Design" },
      { week: 6, session: 2, title: "Authentication and Authorization" },
      { week: 6, session: 3, title: "Encryption and Key Management" },
      { week: 6, session: 4, title: "Security Best Practices" },
      { week: 6, session: 5, title: "Secure System Design" },
      { week: 7, session: 1, title: "Real-time Systems" },
      { week: 7, session: 2, title: "WebSocket Architecture" },
      { week: 7, session: 3, title: "Server-Sent Events" },
      { week: 7, session: 4, title: "Real-time Data Processing" },
      { week: 7, session: 5, title: "Real-time Best Practices" },
      { week: 8, session: 1, title: "Big Data Systems" },
      { week: 8, session: 2, title: "Hadoop Ecosystem" },
      { week: 8, session: 3, title: "Spark and Stream Processing" },
      { week: 8, session: 4, title: "Data Pipeline Design" },
      { week: 8, session: 5, title: "Big Data Architecture" },
      { week: 9, session: 1, title: "Cloud Architecture" },
      { week: 9, session: 2, title: "AWS Services" },
      { week: 9, session: 3, title: "Azure and GCP" },
      { week: 9, session: 4, title: "Multi-Cloud Strategies" },
      { week: 9, session: 5, title: "Cloud Best Practices" },
      { week: 10, session: 1, title: "Containerization and Orchestration" },
      { week: 10, session: 2, title: "Docker Advanced" },
      { week: 10, session: 3, title: "Kubernetes Fundamentals" },
      { week: 10, session: 4, title: "Kubernetes Advanced" },
      { week: 10, session: 5, title: "Container Orchestration" },
      { week: 11, session: 1, title: "System Design Case Studies" },
      { week: 11, session: 2, title: "Designing Twitter" },
      { week: 11, session: 3, title: "Designing Uber" },
      { week: 11, session: 4, title: "Designing Netflix" },
      { week: 11, session: 5, title: "Real-World Systems" },
      { week: 12, session: 1, title: "System Design Interviews" },
      { week: 12, session: 2, title: "Interview Preparation" },
      { week: 12, session: 3, title: "Problem-Solving Framework" },
      { week: 12, session: 4, title: "Communication Skills" },
      { week: 12, session: 5, title: "Career Guidance" },
    ],
  },
};

async function seedAllPlans() {
  try {
    const skillsToSeed = ["Android Development", "Data Structures", "Machine Learning", "System Design"];

    for (const skillName of skillsToSeed) {
      console.log(`\n${"=".repeat(60)}`);
      console.log(`Processing: ${skillName}`);
      console.log("=".repeat(60));

      // Check if plans already exist
      const existing = await prisma.plans.findMany({
        where: { skill_name: skillName },
      });

      if (existing.length > 0) {
        console.log(`⚠️  Plans for "${skillName}" already exist (${existing.length} plans). Skipping...`);
        continue;
      }

      const topics = skillTopics[skillName];
      if (!topics) {
        console.log(`❌ No topic definitions found for "${skillName}". Skipping...`);
        continue;
      }

      // Create Basic Plan
      console.log(`\nCreating Basic Plan...`);
      const basicPlan = await prisma.plans.create({
        data: {
          skill_name: skillName,
          plan_key: "BASIC",
          plan_title: "Basic Plan",
          price: 2999,
          duration_weeks: 4,
          sessions_per_week: 5,
          description: `Perfect for beginners. Learn ${skillName} fundamentals with 5 sessions per week.`,
          is_active: true,
        },
      });
      console.log(`✅ Created Basic Plan (ID: ${basicPlan.id})`);

      // Create topics for Basic Plan
      for (const topic of topics.basic) {
        await prisma.plan_topics.create({
          data: {
            plan_id: basicPlan.id,
            week_number: topic.week,
            session_number: topic.session,
            topic_title: topic.title,
          },
        });
      }
      console.log(`✅ Created ${topics.basic.length} topics for Basic Plan`);

      // Create Standard Plan
      console.log(`\nCreating Standard Plan...`);
      const standardPlan = await prisma.plans.create({
        data: {
          skill_name: skillName,
          plan_key: "STANDARD",
          plan_title: "Standard Plan",
          price: 4999,
          duration_weeks: 8,
          sessions_per_week: 5,
          description: `Most popular choice. Comprehensive ${skillName} learning with 5 sessions per week.`,
          is_active: true,
        },
      });
      console.log(`✅ Created Standard Plan (ID: ${standardPlan.id})`);

      // Create topics for Standard Plan
      for (const topic of topics.standard) {
        await prisma.plan_topics.create({
          data: {
            plan_id: standardPlan.id,
            week_number: topic.week,
            session_number: topic.session,
            topic_title: topic.title,
          },
        });
      }
      console.log(`✅ Created ${topics.standard.length} topics for Standard Plan`);

      // Create Pro Plan
      console.log(`\nCreating Pro Plan...`);
      const proPlan = await prisma.plans.create({
        data: {
          skill_name: skillName,
          plan_key: "PRO",
          plan_title: "Pro Plan",
          price: 7999,
          duration_weeks: 12,
          sessions_per_week: 5,
          description: `Advanced learning path. Master ${skillName} with intensive 5 sessions per week.`,
          is_active: true,
        },
      });
      console.log(`✅ Created Pro Plan (ID: ${proPlan.id})`);

      // Create topics for Pro Plan
      for (const topic of topics.pro) {
        await prisma.plan_topics.create({
          data: {
            plan_id: proPlan.id,
            week_number: topic.week,
            session_number: topic.session,
            topic_title: topic.title,
          },
        });
      }
      console.log(`✅ Created ${topics.pro.length} topics for Pro Plan`);

      console.log(`\n✅ Successfully created all plans and topics for "${skillName}"!`);
    }

    console.log(`\n${"=".repeat(60)}`);
    console.log("✅ Seeding completed!");
    console.log("=".repeat(60));
  } catch (error) {
    console.error("Error seeding plans:", error);
  } finally {
    await prisma.$disconnect();
  }
}

seedAllPlans();

















